[workspace]
members = [
    "hash_emitter"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"


[workspace.dependencies]
alloy-primitives = "=0.8.14"
alloy-sol-types = "=0.8.14"
mini-alloc = "0.4.2"
stylus-sdk = "0.7.0"
hex = "0.4.3"
dotenv = "0.15.0"