[package]
name = "zkleaderboard_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.1", default-features = false, features = ['std'] }
serde = { version = "1.0", default-features = false }
sha2 = { version = "0.10", default-features = false }

